### ISSUE TITLE
The Specialists and Earth's Special Forces Support (Pull Request)

### ISSUE THREAD

**Issue by Aleks-Z** [theAsmodai/metamod-r#15]
Hi.

It's commit which add support of few games (mods) :
- The Specialists
- Earth's Special Forces

Reason for addition is 
- Full support from AmxModX framework. 

Link for proof
- [Site AmxModx](http://www.amxmodx.org/downloads.php)

Link on Pull Request
- #16 

P.S. 
On my practice These mods work with ReHLDS.

**Comment by stamepicmorg** [comment]
hm.. if "The Specialists" mod will be added - it will be great. 👍 i am asking for it early.

-------------------------------

but i am confused with "Earth's Special Forces" linux-mod. because linux-binary directory with so-file have name "linuxdll" against standard "dlls"-folder. 
![123](https://user-images.githubusercontent.com/1307229/28337357-0b70062a-6c0e-11e7-9348-48fdfd8472f7.png)
and metamod-r [searching ](https://github.com/theAsmodai/metamod-r/blob/master/metamod/src/game_support.cpp#L166).dlls\.sos only in "dlls"-folder.

**Comment by stamepicmorg** [comment]
Fixed at https://github.com/theAsmodai/metamod-r/pull/25

**Comment by Aleks-Z** [comment]
I will reopen if there are problems in future
